name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.12.x'
      - uses: gittools/actions/gitversion/execute@v0.9.15
        id: gitversion

      # Build
      - name: Build feed
        run: ./0install.sh run https://apps.0install.net/0install/0template.xml 0watch.xml.template version=${{steps.gitversion.outputs.nuGetVersion}}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: 0watch-${{steps.gitversion.outputs.nuGetVersion}}.*

      # Release
      - name: Create GitHub Release
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: softprops/action-gh-release@v1
        with:
          files: 0watch-${{steps.gitversion.outputs.nuGetVersion}}.*
      - name: Publish feed
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: 0install/apps
          ref: refs/heads/master
          workflow: Incoming
          token: ${{secrets.PERSONAL_TOKEN}}
          inputs: >
            {
              "feed_url": "https://github.com/${{github.repository}}/releases/download/${{steps.gitversion.outputs.nuGetVersion}}/0watch-${{steps.gitversion.outputs.nuGetVersion}}.xml",
              "archive_url": "https://github.com/${{github.repository}}/releases/download/${{steps.gitversion.outputs.nuGetVersion}}/0watch-${{steps.gitversion.outputs.nuGetVersion}}.tar.gz"
            }
