name: Build
on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.5.x'
      - uses: gittools/actions/gitversion/execute@v0.9.7
        id: gitversion

      # Build
      - name: Package
        run: tar -czf 0watch-${{steps.gitversion.outputs.nuGetVersion}}.tar.gz *.py

      # Release
      - name: Create GitHub Release
        if: steps.gitversion.outputs.preReleaseLabel == ''
        uses: softprops/action-gh-release@v1
        with:
          files: 0watch-${{steps.gitversion.outputs.nuGetVersion}}.tar.gz
